In [0]:
import numpy as np
from numpy.linalg import inv

In [0]:
a = np.array([[3., 2.,-1.],[2.,-2.,4.],[-1,1/2,-1]])
b = np.array([1.,-2.,0.])

In [67]:
print(a)
print(b)

[[ 3.   2.  -1. ]
 [ 2.  -2.   4. ]
 [-1.   0.5 -1. ]]
[ 1. -2.  0.]


In [68]:
a_inv=inv(a)
a_inv

array([[ 1.48029737e-16, -5.00000000e-01, -2.00000000e+00],
       [ 6.66666667e-01,  1.33333333e+00,  4.66666667e+00],
       [ 3.33333333e-01,  1.16666667e+00,  3.33333333e+00]])

In [69]:
A_=np.linalg.det(a)
print(A_)

-3.0000000000000036


In [74]:
np.dot(a_inv,b)

array([ 1., -2., -2.])

In [0]:
#=====================================================================================================

In [73]:
z=np.linalg.solve(a,b)
print(z)

[ 1. -2. -2.]
